### ISSUE TITLE
Update Word styling

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ribose#41]
MN source: https://gitlab.com/ribose/ribose-open-docs

Post-modification DOCX: https://gitlab.com/ribose/ribose-open-docs/-/releases

**Comment by ronaldtse** [comment]
Internal source: https://github.com/ribosei/mn-internal-samples-rsd

Post-modification DOCX inside repo.

**Comment by opoudjis** [comment]
is this the work I have just been doing under #39? If so, let's get rid of this ticket.

**Comment by opoudjis** [comment]
What are the document types?
What are the identifier prefixes corresponding to the document types?
What are the possible values substituting "Ribose Asia Limited"? These are presumably the publisher?
Do all documents have a recipient? ("Delivered to:") Is the recipient only ever specified as an email address?

**Comment by opoudjis** [comment]
@ronaldtse FYI this ticket is on hold pending your feedback as to further work.

**Comment by ronaldtse** [comment]
> What are the document types?

https://github.com/metanorma/metanorma-model-rsd
<img width="211" alt="Screen Shot 2020-12-07 at 10 40 29 AM" src="https://user-images.githubusercontent.com/11865/101303277-a0cdb980-3878-11eb-9f57-438e866a2823.png">

> What are the identifier prefixes corresponding to the document types?

Do you need a pattern or can we decide this later?

> What are the possible values substituting "Ribose Asia Limited"? These are presumably the publisher?

Yes. Let's make it configurable.

> Do all documents have a recipient? ("Delivered to:") Is the recipient only ever specified as an email address?

Not all documents have a recipient. Not always an email address. Let's make it freeform text.

**Comment by opoudjis** [comment]
metanorma.yml altered:

````
metanorma_name: ribose
organization_name_short: Ribose
organization_name_long: Ribose Asia Limited
doctypes:
  standard:
  code: Code
  presentation: Pres
  proposal: Prop
  report: Rept
  specification: Spec
````

Recipient is not mandatory, and is not required to be email.
